# Generated by Django 4.2.6 on 2023-12-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacherstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherStudent',
        ),
    ]
